// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BerryPin struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Lat       float64
	Lng       float64
	BerryType string
	Notes     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
