// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type BerryPin struct {
	ID        string
	UserID    string
	Lat       float64
	Lng       float64
	BerryType string
	Notes     string
	CreatedAt string
	UpdatedAt string
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	CreatedAt    string
}
