// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pins.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPin = `-- name: CreatePin :one
INSERT INTO berry_pins (user_id, lat, lng, berry_type, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, lat, lng, berry_type, notes, created_at, updated_at
`

type CreatePinParams struct {
	UserID    uuid.UUID
	Lat       float64
	Lng       float64
	BerryType string
	Notes     string
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) (BerryPin, error) {
	row := q.db.QueryRow(ctx, createPin,
		arg.UserID,
		arg.Lat,
		arg.Lng,
		arg.BerryType,
		arg.Notes,
	)
	var i BerryPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Lat,
		&i.Lng,
		&i.BerryType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePin = `-- name: DeletePin :exec
DELETE FROM berry_pins
WHERE id = $1 AND user_id = $2
`

type DeletePinParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) error {
	_, err := q.db.Exec(ctx, deletePin, arg.ID, arg.UserID)
	return err
}

const getPin = `-- name: GetPin :one
SELECT id, user_id, lat, lng, berry_type, notes, created_at, updated_at
FROM berry_pins
WHERE id = $1
`

func (q *Queries) GetPin(ctx context.Context, id uuid.UUID) (BerryPin, error) {
	row := q.db.QueryRow(ctx, getPin, id)
	var i BerryPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Lat,
		&i.Lng,
		&i.BerryType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPins = `-- name: ListPins :many
SELECT id, user_id, lat, lng, berry_type, notes, created_at, updated_at
FROM berry_pins
ORDER BY created_at DESC
`

func (q *Queries) ListPins(ctx context.Context) ([]BerryPin, error) {
	rows, err := q.db.Query(ctx, listPins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BerryPin
	for rows.Next() {
		var i BerryPin
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Lat,
			&i.Lng,
			&i.BerryType,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePin = `-- name: UpdatePin :one
UPDATE berry_pins
SET notes = $2, berry_type = $3, updated_at = now()
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, lat, lng, berry_type, notes, created_at, updated_at
`

type UpdatePinParams struct {
	ID        uuid.UUID
	Notes     string
	BerryType string
	UserID    uuid.UUID
}

func (q *Queries) UpdatePin(ctx context.Context, arg UpdatePinParams) (BerryPin, error) {
	row := q.db.QueryRow(ctx, updatePin,
		arg.ID,
		arg.Notes,
		arg.BerryType,
		arg.UserID,
	)
	var i BerryPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Lat,
		&i.Lng,
		&i.BerryType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
