// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pins.sql

package sqlc

import (
	"context"
)

const createPin = `-- name: CreatePin :one
INSERT INTO berry_pins (id, user_id, lat, lng, berry_type, notes)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, lat, lng, berry_type, notes, created_at, updated_at
`

type CreatePinParams struct {
	ID        string
	UserID    string
	Lat       float64
	Lng       float64
	BerryType string
	Notes     string
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) (BerryPin, error) {
	row := q.db.QueryRowContext(ctx, createPin,
		arg.ID,
		arg.UserID,
		arg.Lat,
		arg.Lng,
		arg.BerryType,
		arg.Notes,
	)
	var i BerryPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Lat,
		&i.Lng,
		&i.BerryType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePin = `-- name: DeletePin :exec
DELETE FROM berry_pins
WHERE id = ? AND user_id = ?
`

type DeletePinParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) error {
	_, err := q.db.ExecContext(ctx, deletePin, arg.ID, arg.UserID)
	return err
}

const getPin = `-- name: GetPin :one
SELECT id, user_id, lat, lng, berry_type, notes, created_at, updated_at
FROM berry_pins
WHERE id = ?
`

func (q *Queries) GetPin(ctx context.Context, id string) (BerryPin, error) {
	row := q.db.QueryRowContext(ctx, getPin, id)
	var i BerryPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Lat,
		&i.Lng,
		&i.BerryType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPins = `-- name: ListPins :many
SELECT id, user_id, lat, lng, berry_type, notes, created_at, updated_at
FROM berry_pins
ORDER BY created_at DESC
`

func (q *Queries) ListPins(ctx context.Context) ([]BerryPin, error) {
	rows, err := q.db.QueryContext(ctx, listPins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BerryPin
	for rows.Next() {
		var i BerryPin
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Lat,
			&i.Lng,
			&i.BerryType,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePin = `-- name: UpdatePin :one
UPDATE berry_pins
SET notes = ?, berry_type = ?, updated_at = datetime('now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, lat, lng, berry_type, notes, created_at, updated_at
`

type UpdatePinParams struct {
	Notes     string
	BerryType string
	ID        string
	UserID    string
}

func (q *Queries) UpdatePin(ctx context.Context, arg UpdatePinParams) (BerryPin, error) {
	row := q.db.QueryRowContext(ctx, updatePin,
		arg.Notes,
		arg.BerryType,
		arg.ID,
		arg.UserID,
	)
	var i BerryPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Lat,
		&i.Lng,
		&i.BerryType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
