name: Seed user

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username for the new user"
        required: true
      password:
        description: "Password for the new user"
        required: true

jobs:
  seed-user:
    runs-on: ubuntu-latest

    steps:
      - name: Seed user on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/marjakartta/backend
            source .env
            ./seed "${{ inputs.username }}" "${{ inputs.password }}"
